language: ruby
rvm:
  - 2.0.0
  - 2.1.0
  - 2.2.0
notifications:
  email: false
bundler_args: --without guard watch
script: bundle exec rake
env:
  - RAILS_VERSION=4.2.5
  - RAILS_VERSION=5.0.0
matrix:
  # don't run rails 5 on ruby versions that can't install rack 2
  exclude:
    - rvm: 2.0.0
      env: RAILS_VERSION=5.0.0
    - rvm: 2.1.8
      env: RAILS_VERSION=5.0.0
