language: ruby
rvm:
  - 2.0
  - 2.1
  - 2.2
  - 2.3
  - 2.4
bundler_args: --without guard watch bench
script: bundle exec rake
env:
  - RAILS_VERSION=4.2.5
  - RAILS_VERSION=5.0.0
matrix:
  # don't run rails 5 on ruby versions that can't install rack 2
  exclude:
    - rvm: 2.0
      env: RAILS_VERSION=5.0.0
    - rvm: 2.1
      env: RAILS_VERSION=5.0.0
